services:
  db:
    image: postgres:15-alpine
    container_name: pos_db
    env_file: .env
    environment:
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    # 🛠️ AGREGAMOS ESTO: Sube el límite a 100 conexiones para que convivan Spring Boot y DBeaver
    command: ["postgres", "-c", "max_connections=100"]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - pos-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 10s
      retries: 5

  app:
    build: .
    env_file: .env
    container_name: pos_api_app
    ports:
      - "${APP_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://pos_db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none # Desactivado para usar Flyway
      # 🛡️ Variables de entorno críticas pasadas de forma explícita
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SPRING_AI_OLLAMA_BASE_URL: ${SPRING_AI_OLLAMA_BASE_URL}
      SPRING_MVC_PATHMATCH_MATCHING_STRATEGY: ant_path_matcher
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pos-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  pos-network:
    driver: bridge

volumes:
  db_data:
