server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: pos-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB:pos_db}
    username: ${SPRING_DATASOURCE_USERNAME:product}
    password: ${SPRING_DATASOURCE_PASSWORD:product123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  show-actuator: false

  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: llama3.2


app:
  jwt:
    secret: ${JWT_SECRET:dGhpc2lzYW5leG1wbGViYXM2NHNlY3JldGZvcSFRTUMyNTY=}
    expiration-in-ms: ${JWT_EXPIRATION:3600000} # 1 hora
  bootstrap:
    admin:
      email: ${ADMIN_EMAIL:admin@posapi.com}
      password: ${ADMIN_PASSWORD:SuperSecretPassword123!}
      full-name: ${ADMIN_FULL_NAME:Admin User}     # <-- Agregado
      address: ${ADMIN_ADDRESS:Bellavista, Queretaro} # <-- Agregado

logging:
  level:
    com.posapi: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: DEBUG
    org.springframework.security.access: DEBUG
    org.hibernate.tool.hbm2ddl: DEBUG
