# Propiedades del administrador para el BootstrapService (usando variables de entorno)
admin.email=${ADMIN_EMAIL:admin@posapi.com}
admin.password=${ADMIN_PASSWORD:admin}
admin.fullName=${ADMIN_FULL_NAME:Admin User}
