# ===================================================================
# CONFIGURACIÓN DE SPRING BOOT PARA EL PERFIL 'DOCKER'
# ===================================================================
# Estas propiedades sobrescriben las de 'application.yml' cuando
# la aplicación se ejecuta dentro de un contenedor Docker.

spring:
  datasource:
    # Dentro de la red de Docker, nos conectamos al servicio 'db' en lugar de 'localhost'.
    url: jdbc:postgresql://db:5432/${POSTGRES_DB:pos_db}
    username: ${POSTGRES_USER:product}
    password: ${POSTGRES_PASSWORD:product123}
  jpa:
    hibernate:
      # En el entorno de Docker, es seguro que Hibernate actualice el esquema.
      ddl-auto: update
  rabbitmq:
    # Dentro de la red de Docker, nos conectamos al servicio 'rabbitmq' (si lo tuvieras).
    host: rabbitmq
