# ===================================================================
# CONFIGURACIÓN DE SPRING BOOT PARA EL PERFIL 'DOCKER'
# ===================================================================
# Estas propiedades sobrescriben las de 'application.yml' cuando
# la aplicación se ejecuta dentro de un contenedor Docker.

spring:
  datasource:
    # Dentro de la red de Docker, nos conectamos al servicio 'pos_db' en lugar de 'localhost'.
    url: jdbc:postgresql://pos_db:5432/${POSTGRES_DB:pos_db}
    username: ${POSTGRES_USER:product}
    password: ${POSTGRES_PASSWORD:product123}
  jpa:
    hibernate:
      # En el entorno de Docker, Flyway maneja el esquema, por lo que Hibernate solo debe validar.
      ddl-auto: validate
  rabbitmq:
    # Dentro de la red de Docker, nos conectamos al servicio 'rabbitmq' (si lo tuvieras).
    host: rabbitmq
