# Server Port
server:
  port: 8080

# Datasource Configuration (for local IDE execution)
# These will be overridden by environment variables when running with Podman
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pos_db
    username: pos_user
    password: pos_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    # 'none' because we are managing the schema with SQL scripts (V1, V2)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    gateway:
      routes:
        - id: rate_limit_route
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/users/register
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 5

# JWT Security Configuration (Required for Integration Tests)
jwt:
  # Preferible: usa una clave Base64 segura. Ejemplo comentado abajo.
  # secret: "dGhpc2lzYW5leGFtcGxlYmFzZTY0c2VjcmV0Zm9ySFRNQw=="
  secret: "clavesecretadebackendedeseguridadsuperlargade64bytes12345"
  # Duración del token en milisegundos (1h por defecto)
  expiration: 3600000

# Logging
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

